### ISSUE TITLE
Could you provide an annotaion file of each cell

### ISSUE THREAD

**Issue by pangxueyu233** [williamsdrake/oralAtlas#1]
Hi, 

It's really a nice study for researchers in fields. And this project had provided a valuable single cell data of oral tissue. Recently, we want to combine these data into our study, but we cannot find the annotaion file of each cells. We want to generate the consistant  single cell map mentinoned in your study , could you provide an annotaion file for each cell?

Thanks !

**Comment by williamsdrake** [comment]
Thanks for your interest in our dataset.

Annotated objects can be found at https://oral.cellatlas.io/

**Comment by pangxueyu233** [comment]
@williamsdrake 
I had visited this page before, but I cannot download the h5ad files. The button of download was not accessible.
![image](https://user-images.githubusercontent.com/40414477/123908202-abcd7000-d9a9-11eb-942d-8148e4952a9e.png)

**Comment by williamsdrake** [comment]
Thanks for your patience. The download button should work now.
